### ISSUE TITLE
Account "validator" does not exist

### ISSUE THREAD

**Issue by jonas089** [provenance-io/provwasm#116]
There seems to be no default faucet account that I can use to fund new accounts.
Please help me understand how to properly fund accounts on a local testnet. 
Kind regards.

**Comment by kwtalley** [comment]
Here is the [initialize script](https://github.com/provenance-io/provenance/blob/357c36b34030933482c65b11b9747841228e2376/scripts/initialize.sh) used for development and can be used as a reference. It shows how accounts can be created and funded prior to starting the local testnet.

If the testnet is running, funds can be transferred as referenced in this [contract test script](https://github.com/provenance-io/provwasm/blob/ef2dba47eaf216a6c7d33698761b96328a277c4b/scripts/gh-action-test/msgfees_test.sh#L20)

**Comment by Taztingo** [comment]
You may want to verify that you are using the correct home directory. Once you are sure you are using the correct home directory, then you should be able to run `provenanced -t keys list` and see your list of keys.
