### ISSUE TITLE
Update template contract

### ISSUE THREAD

**Issue by Taztingo** [provenance-io/provwasm#126]
## Summary

The template contract should be updated to use provwasm 2.0, and it should also use the latest optimizer 0.14.0.

## Problem Definition

The optimizer isn't consistent across the Makefile and the cargo metadata scripts. They are not the same version so there may be times where optimization fails and it can be hard to debug. This failure is from older optimizer versions.

## Proposal

Update provwasm in Makefile.
Update optimizer version in Makefile
Update optimizer version in Cargo.toml

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by kwtalley** [comment]
closed by #129
