### ISSUE TITLE
Build a contract to handle tagging of NAVs

### ISSUE THREAD

**Issue by Taztingo** [provenance-io/provwasm#138]
## Summary

It would be helpful if there was a way to introduce adding tags to NAVs. These tags would allow us to add a custom descriptor to our assets and allow us to easily query them. One approach is to have a contract act as prototype before we decide to implement this into the protocol.

## Problem Definition

Provenance users can tag their assets by creating entries within the attributes modules. However, this can be cumbersome and a nuisance to work with. A contract would ease the amount of work needed by our users.

## Proposal

- Create a contract that allows us to add custom tags to assets
- The contract should be add or modify tags on assets
- The contract should also be allowed to query by tag or asset.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by kwtalley** [comment]
closed with #139
