### ISSUE TITLE
Bilateral Exchange Smart Contract

### ISSUE THREAD

**Issue by jdfigure** [provenance-io/provwasm#19]
Develop a bilateral exchange smart contract utilized by Figure marketplace

## Problem Statement
Marketplace needs a bilateral exchange of value, which is atomic and is controlled on chain(not through clients) for e.g exchange markers for stable coin or even one stable coin for another.Transfer marker a(pool of loans) -> for marker b(stable coin) from acc 1 -> acc 2 where a and b are both guaranteed the exchange will settle immediately between acc1 and acc2.

_This should in our view involve creation of a smart contract which can do this exchange._ 

### Proposed Solution

Smart contract owns marker pool a(smart contract owned by accnt 1 or trusted escrow/custodian)
--> publishes
--> when it receives stable coin b( i.e the ask for the contract)
--> it transfer's the collateral (marker a) to acct2
--> transfer marker a to accnt 1

contract has an `owner/creator`

contract owns `marker a`

handle method:

exercise (transfer collateral marker a to acct2.. transfer stable coin marker 2 to accnt 1 )

maybe transfer and burn/destroy methods also

A great example is the SimpleOption smart contract example in cosmwasm.

**Comment by ktalley-figure** [comment]
this contract has been created in another repo: https://github.com/provenance-io/bilateral-exchange
