### ISSUE TITLE
Allow zero marker supply

### ISSUE THREAD

**Issue by tsilva-figure** [provenance-io/provwasm#48]
https://github.com/provenance-io/provwasm/blob/5ff4c8cd4d59ee0a380eae4d3c95aac1785cbafd/packages/bindings/src/msg.rs#L337

**Comment by dpederson-figure** [comment]
It is possible to create a marker with a supply of zero, as long as some address has 'mint' permissions.  Remove the validation check in `create_marker` that returns an error when the requested supply is zero.

**Comment by dpederson-figure** [comment]
Merged to main; will cut the v0.14.3 release before EOD Friday Jul 23.
