### ISSUE TITLE
All permissions grant on markers regardless of marker type

### ISSUE THREAD

**Issue by iramiller** [provenance-io/provwasm#53]
https://github.com/provenance-io/provwasm/blob/e7922314bff482099554e41233be28076489a880/contracts/marker/src/contract.rs#L76

The approach of assigning all access rights to a marker regardless of need/configuration is a potential issue when validation prevents assignment of the `transfer` role to a unrestricted aka `COIN` type markers.  This constraint has been on the list to add to the marker module but thankfully hasn't been implemented yet because this code would break.

This is also a bit risky in the future as there are other types under consideration that would potentially add further access right options which would be incompatible with the other marker types.

**Comment by kwtalley** [comment]
closed with new proto based provwasm #114
