### ISSUE TITLE
Allow Governance property is missing on marker schema

### ISSUE THREAD

**Issue by iramiller** [provenance-io/provwasm#54]
https://github.com/provenance-io/provwasm/blob/e7922314bff482099554e41233be28076489a880/contracts/marker/schema/marker.json#L15

The `AllowGovernanceControl` field is missing on the marker schema:

https://github.com/provenance-io/provenance/blob/c0aa06e602fbddbadfe0d58ee10167a0fc1bdaec/x/marker/types/marker.pb.go#L180

**Comment by kwtalley** [comment]
closed with new proto based provwasm #114
