### ISSUE TITLE
Uploading wasm binary fails with unknown interface_version_* marker export

### ISSUE THREAD

**Issue by dmtrinh** [provenance-io/provwasm#70]
I built my own helloworld contract and tried uploading the optimized binary to a local Provenance network and it failed.  Out of curiosity, I tried following the latest tutorial instructions and got the same failure on [Step 9](https://github.com/provenance-io/provwasm/blob/main/docs/tutorial/09-store.md)

## Summary of Bug

Uploading wasm binary fails with the following error

```
(base) ---------- 21:04:50 (duc@DucMacBook) :~/Dev/provenance ----------
==> provenanced tx wasm store tutorial.wasm \
    --instantiate-only-address tp1aht5v4wxq0qsh96aa8kxuwg5sd2mj5a5d2my2n \
    --from tp1aht5v4wxq0qsh96aa8kxuwg5sd2mj5a5d2my2n \
    --keyring-backend test \
    --home build/node0 \
    --chain-id chain-local \
    --gas auto \
    --gas-prices="1905nhash" \
        --gas-adjustment=1.5 \
    --broadcast-mode block \
    --yes \
    --testnet \
        --output json | jq
Error: rpc error: code = InvalidArgument desc = failed to execute message; 
message index: 0: Error calling the VM: Error during static Wasm validation: 
Wasm contract has unknown interface_version_* marker export 
(see https://github.com/CosmWasm/cosmwasm/blob/main/packages/vm/README.md): 
create wasm contract failed: invalid request
```

## Version
Latest tutorial codebase from https://github.com/provenance-io/provwasm

## Steps to Reproduce
Follow tutorial @ https://github.com/provenance-io/provwasm/blob/main/docs/tutorial/01-overview.md

____

## For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned

**Comment by ktalley-figure** [comment]
Hello, do you have the specific git commits or versions of Provenance and ProvWasm? This error suggests a version mismatch. The latest ProvWasm bindings 1.0.0-beta2 are compatible with the latest Provenance 1.8.0 release candidates

**Comment by ktalley-figure** [comment]
Checking in again. If everything is alright I will close the issue soon.
