### ISSUE TITLE
Upgrade to CosmWasm 1.0.0-rc0

### ISSUE THREAD

**Issue by ktalley-figure** [provenance-io/provwasm#83]
## Summary
CosmWasm 1.0.0-rc0 was released and Provwasm should be upgraded to it

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned

**Comment by iramiller** [comment]
Related: https://github.com/CosmWasm/wasmd/releases/tag/v0.27.0-rc0
